### PR TITLE
Add banner

### PR DESCRIPTION
**Pull request by cmaureir**

### CODE REVIEW

**Comment by cmaureir** [comment]
Screenshot 2024-09-20 at 11-39-16 PyLadiesCon 2024

Just an idea. I really dislike the gray we have at the moment :P 
(cc @georgically  )

**Comment by georgically** [comment]
I agree with the grey but the red is not very readable on the blue either.

**Comment by cmaureir** [comment]
What about a slight lighter blue?
I just want to replace the gray background...it looks terrible.

localhost_1313_

**Review by willingc — APPROVED** [review]
Oooh pretty. Thanks @cmaureir

**Comment by cmaureir** [comment]
Superseded by https://github.com/pyladies/global-conference/pull/150 (Thanks @willingc anyways!)

**Pull request closed without merging**
